name: coin_pay
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^2.7.0
  flutter_nfc_kit: ^3.4.2
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.3.0
  google_fonts: ^6.1.0
  provider: ^6.0.5
  http: ^1.1.0  
  flutter_web_auth_2: ^4.1.0
  dio: ^5.4.0
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
